### ISSUE TITLE
project join

### ISSUE THREAD

**Issue by rubydesign** [TheArtificial/rails-wiki#9]
hi gerwitz

i just wanted to say that i'd be very happy to join forces with you and dump my project.

What you so aptly noticed about my engine (confusingly doesn't use gollum_lib) has a history, as does the project.
I needed, like you, a rails engine and approached florian. He shortly after got a no from his boss, so i was on my own and the gollum guys didn't help until they came with a rewrite. Bad cooperation all way round.

But the silliest thing is, my project went south and i don't even need the thing. 

But i have written about 10 engines, so maybe i can help. And you are more than welcome to copy any code i have.

Torsten

**Comment by gerwitz** [comment]
Thanks! I haven't thoroughly poked through your project yet, but will make a point of it. If you know of anyone actively using it, I'd love to have some extra eyes as I try to make a proper tool of this.

Any direct help is of course very welcome. Especially getting some tests in place. ;-)

(I'll leave this issue open as a reminder to audit https://github.com/dancinglightning/gollum_rails for compatibility.)

**Comment by rubydesign** [comment]
I don't know anyone who uses my tool, as it's not even me.

But i did have good tests. I used spec though how are your with that ?

Maybe we can go through the code together sometimes. gitter or hangout

**Comment by gerwitz** [comment]
+1 let's have a gitter session in the new year. Maybe by then I'll even have some Rspec set up.
